[telegram]
# telegram bot token, e.g. "1234567890:ABCDEF1234567890ABCDEF1234567890ABC"
token = "1234567890:ABCDEF1234567890ABCDEF1234567890ABC"


[mastodon]
# api base url, e.g. "mastodon.social"
api_base_url = "mastodon.social"

# access token for the bot account
# create a new application at https://<api_base_url>/settings/applications/new
# the following permissions are required:
#   read:accounts 
#   read:statuses   (optional, if you want to forward toot to telegram)
#   write:media     (optional, if you want to forward media to mastodon)
#   write:statuses  (optional, if you want to forward toot to mastodon)
access_token = "ABCDEF1234567890ABCDEF1234567890ABCDEF12345"


[options]

[options.telegram_to_mastodon]
# whether to forward messages from telegram to mastodon
disable = false

# channel or group chat id for messages forwarding
# if you use a channel, the success of the forwarding will be reported to the private chat
# if you use a group, the success of the forwarding will be reported to the group by replying to the forwarded message
channel_chat_id = -1000000000000

# private chat id for exceptions reporting
# you should create a private chat with the bot using /start command
pm_chat_id = 0


[options.telegram_to_mastodon.filter]
# optional, filters for messages forwarding
# if the message contains any of the tags, it will be forwarded, otherwise ignored
# espacially, if include is empty, all messages will be forwarded
# (except those that contain tags from exclude)
include = []

# optional, filters for messages forwarding
# if the message contains any of the tags, it will be ignored, otherwise forwarded
exclude = ["#nofwd", "#noforward", "#mastodon"]


[options.telegram_to_mastodon.footer]
# whether to add a link to the original post
add_link = false

# whether to show the original post author
show_forward_from = true


[options.mastodon_to_telegram]
# whether to forward messages from mastodon to telegram
disable = false

# channel or group chat id for messages forwarding 
# can be different from the one used for telegram_to_mastodon
channel_chat_id = -1000000000000

# private chat id for exceptions reporting
# can be different from the one used for telegram_to_mastodon
pm_chat_id = 0

# if true, will forward only the link to the original post
# please note that the link will be added to the footer, so add_link in footer should be true
# and the original post should be public or the link can not be accessed by others
forward_reblog_link_only = true


[options.mastodon_to_telegram.filter]
# the scope should be forward to telegram
# if the status is a reblog, the scope of the original post WON'T be checked by this filter
scope = ["public", "unlisted"]

# if you want to check the scope of the original post, use a custom filter to check it
# reblogged_scope = ["public", "unlisted"]

[options.mastodon_to_telegram.footer]
# whether to add a link to the original post
add_link = true

# optional, additional tags to add to the message
tags = ["#mastodon"]
