from typing import Type, overload

from .filter import Filter
from .footer import Footer
from .main import main


@overload
def custom_bridge(*, mastodon_filter: Type[Filter]) -> None: ...
@overload
def custom_bridge(*, telegram_filter: Type[Filter]) -> None: ...
@overload
def custom_bridge(*, mastodon_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], telegram_filter: Type[Filter]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], mastodon_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, telegram_filter: Type[Filter], mastodon_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, telegram_filter: Type[Filter], telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_footer: Type[Footer], telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], telegram_filter: Type[Filter], mastodon_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], telegram_filter: Type[Filter], telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, mastodon_filter: Type[Filter], mastodon_footer: Type[Footer], telegram_footer: Type[Footer]) -> None: ...
@overload
def custom_bridge(*, telegram_filter: Type[Filter], mastodon_footer: Type[Footer], telegram_footer: Type[Footer]) -> None: ...


@overload
def custom_bridge(*,
         mastodon_filter: Type[Filter], telegram_filter: Type[Filter],
         mastodon_footer: Type[Footer], telegram_footer: Type[Footer]) -> None: ...


def custom_bridge(**kargs):
    main(**kargs)
